model_structure: erfnet
dataset_path: /home/lennard/Datasets/Cityscapes/
epochs: 100
learning_rate: 1e-2
batch_sizes:
  train: 1
  validation: 1
  test: 1
image_size:
  - 512
  - 1024
n_classes: 19
normalization_params:
  - [72.45996064, 82.30920661, 71.8585933]
  - [46.99697658, 47.7633243, 46.96281819]
class_labels:
  - [[128, 64,128], "road"]
  - [[244, 35,232], "sidewalk"]
  - [[ 70, 70, 70], "building"]
  - [[102,102,156], "wall"]
  - [[190,153,153], "fence"]
  - [[153,153,153], "pole"]
  - [[250,170, 30], "traffic light"]
  - [[220,220,  0], "traffic sign"]
  - [[107,142, 35], "vegetation"]
  - [[152,251,152], "terrain"]
  - [[ 70,130,180], "sky"]
  - [[220, 20, 60], "person"]
  - [[255,  0,  0], "rider"]
  - [[  0,  0,142], "car"]
  - [[  0,  0, 70], "truck"]
  - [[  0, 60,100], "bus"]
  - [[  0, 80,100], "train"]
  - [[  0,  0,230], "motorcycle"]
  - [[119, 11, 32], "bicycle"]
  - [[  0,  0,  0], "void"]
class_mapping: [-1, -1, -1, -1, -1, -1, -1, 0, 1, -1, -1, 2, 3, 4, -1, -1, -1, 5, -1, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1, -1, 16, 17, 18]