model_structure: u_net
dataset_path: /home/lennard/Datasets/Cityscapes/
epochs: 1000
learning_rate: 1e-3
batch_sizes:
  train: 1
  validation: 1
  test: 1
image_size:
  - 512
  - 1024
n_classes: 19
write_test_results: False
load_path: results/u_net_18-11-11_220228/saved_model/model.ckpt
