model_structure: u_net
dataset_path: /home/lennard/Datasets/Cityscapes/
epochs: 1000
learning_rate: 1e-3
batch_sizes:
  train: 1
  validation: 1
  test: 1
image_size:
  - 512
  - 1024
n_classes: 19
write_test_results: False
normalization_params:
  - [72.45996064, 82.30920661, 71.8585933]
  - [46.99697658, 47.7633243, 46.96281819]
