model_structure: erfnet
dataset_path: /home/lennard/Datasets/electron_microscopy/
epochs: 50
learning_rate: 1e-4
batch_sizes:
  train: 1
  validation: 1
  test: 1
image_size:
  - 768
  - 1024
n_classes: 2
class_weights: [0.1, 8.73221320017] #0.02862962622
use_augs: False
class_labels:
  - [[  0,  0,  0], "background"]
  - [[255,  255,  255], "mitochondria"]
pre_training: cityscapes
load_path: /home/lennard/PycharmProjects/tensorflow_vocalfolds/results/best_results/erfnet/cityscapes/saved_model/erfnet.ckpt
