# This config file performs a training on the mitochondrial dataset

model_structure: deeplab
dataset_path: /home/lennard/Datasets/electron_microscopy/
epochs: 30
learning_rate: 1e-4
batch_sizes:
  train: 1
  validation: 1
  test: 1
image_size:
  - 768
  - 1024
n_classes: 2
class_weights: [0.1, 8.73221320017]
use_augs: False
class_labels:
  - [[  0,  0,  0], "background"]
  - [[255,  255,  255], "mitochondria"]
load_path: results/final_experiments/electron_microscopy/pre-training/deeplab_cs/deeplab_v3_plus_19-03-24_103636/saved_model/deeplab_v3_plus.ckpt
