model_structure:
  - u_net
  - segnet
dataset_path: /home/lennard/Datasets/vocalfolds-master/
epochs: 10
learning_rate: 1e-4
batch_sizes:
  train: 1
  validation: 1
  test: 1
image_size:
  - 512
  - 512
n_classes: 7
class_weights: [6.63673196, 0.35289383, 0.39340525, 1.39874843, 35.46317718, 5.05643017, 1.87683896]
use_augs: False
normalization_params:
  - [160.99123017, 92.29408995, 72.23536678]
  - [59.28851215, 46.16065498, 43.67935978]
class_labels:
  - [[105,105,105], "void"]
  - [[255,  0,  0], "vocal folds"]
  - [[  0,  0,255], "other tissue"]
  - [[  0,255,  0], "glottal space"]
  - [[128,  0,128], "pathology"]
  - [[255, 69,  0], "surgical tool"]
  - [[255,255,  0], "intubation"]
load_path:
  - results/best_results/u_net/saved_model/model.ckpt
  - results/best_results/segnet/saved_model/model.ckpt
