# This cofig performs a training of an ensemble of models on the vocal folds dataset

model_structure:
  - unet
  #- enet
  - erfnet
  #- deeplab
dataset_path: /home/lennard/Datasets/vocalfolds_augmented_big/
epochs: 3
learning_rate: 1e-4
batch_sizes:
  train: 1
  validation: 1
  test: 1
image_size:
  - 512
  - 512
n_classes: 6
class_weights: [0.35289383, 0.39340525, 1.39874843, 35.46317718, 5.05643017, 1.87683896]
use_augs: False
class_labels:
  - [[255,  0,  0], "vocal folds"]
  - [[  0,  0,255], "other tissue"]
  - [[  0,255,  0], "glottal space"]
  - [[128,  0,128], "pathology"]
  - [[255, 69,  0], "surgical tool"]
  - [[255,255,  0], "intubation"]
class_mapping: [-1, 0, 1, 2, 3, 4, 5]
load_path:
  - results/u_net_19-03-27_234311/saved_model/u_net.ckpt
  - results/final_experiments/vocalfolds/augmentations/all/erfnet/erfnet_19-03-15_173756/saved_model/erfnet.ckpt
  #- results/final_experiments/vocalfolds/augmentations/all/deeplab/deeplab_v3_plus_19-03-16_160608/saved_model/deeplab_v3_plus.ckpt
